pipeline
{
  agent any
  stages{
    
    stage('Build Application'){
      steps{
        bat 'cd world-timezone-api & mvn clean install'
      }
    }
    
    stage('Unit Test Application'){
      steps{
        bat 'cd world-timezone-api & mvn clean test'
      }
    }

    stage('Deploy Application To Mulesoft CloudHub'){
      steps{
        bat 'cd world-timezone-api & mvn package deploy -DmuleDeploy'
      }
    }
    stage('Perform Regression Testing'){
      steps{
        bat 'C:\\Users\\uday\\AppData\\Roaming\\npm\\newman run E:\\TestTools\\postman\\WorldTimeZone.postman_collection.json --disable-unicode'
      }
    }    
  }	
}